/* ###################################### */
/* ###     Frost Engine, by Kalith    ### */
/* ###################################### */
/*                                        */

#include "frost_uiobject.h"
#include "frost_frame.h"
#include "frost_layeredregion.h"
#include "frost_button.h"
#include "frost_checkbutton.h"
#include "frost_editbox.h"
#include "frost_messageframe.h"
#include "frost_scrollframe.h"
#include "frost_scrollingmessageframe.h"
#include "frost_slider.h"
#include "frost_statusbar.h"
#include "frost_fontstring.h"
#include "frost_texture.h"

/****************/
/* Methods list */
/****************/

/* [#] Here we register every member function of each class. As Lunar doesn't
*  know about inheritance, you're obliged to register every member function of a
*  C++ class, including the ones inherited. Else you won't be able to call them
*  in LUA.
*/

#define method(widget, function) {#function, &Lua##widget::_##function}

namespace Frost
{
namespace GUI
{
    const char LuaVirtualGlue::className[] = "VirtualGlue";
    const char* LuaVirtualGlue::classList[] = {"VirtualGlue", 0};
    Lunar<LuaVirtualGlue>::RegType LuaVirtualGlue::methods[] = {
        {"dt", &LuaVirtualGlue::GetDataTable},

        // VirtualGlue
        method(VirtualGlue, MarkForCopy),
        method(VirtualGlue, GetBase),
        method(VirtualGlue, GetName),

        {0,0}
    };

    const char LuaUIObject::className[] = "UIObject";
    const char* LuaUIObject::classList[] = {"UIObject",
        "Frame", "Button", "CheckButton", "EditBox", "MessageFrame", "ScrollFrame",
        "ScrollingMessageFrame", "Slider", "StatusBar", "LayeredRegion", "Texture", "FontString", 0
    };
    Lunar<LuaUIObject>::RegType LuaUIObject::methods[] = {
        {"dt", &LuaUIObject::GetDataTable},

        // UIObject
        method(UIObject, GetAlpha),
        method(UIObject, GetName),
        method(UIObject, GetObjectType),
        method(UIObject, IsObjectType),
        method(UIObject, SetAlpha),

        method(UIObject, ClearAllPoints),
        method(UIObject, GetBase),
        method(UIObject, GetBottom),
        method(UIObject, GetCenter),
        method(UIObject, GetHeight),
        method(UIObject, GetLeft),
        method(UIObject, GetNumPoint),
        method(UIObject, GetParent),
        method(UIObject, GetPoint),
        method(UIObject, GetRight),
        method(UIObject, GetTop),
        method(UIObject, GetWidth),
        method(UIObject, Hide),
        method(UIObject, IsShown),
        method(UIObject, IsVisible),
        method(UIObject, SetAllPoints),
        method(UIObject, SetHeight),
        method(UIObject, SetParent),
        method(UIObject, SetPoint),
        method(UIObject, SetRelPoint),
        method(UIObject, SetWidth),
        method(UIObject, Show),
        {0,0}
    };

    const char  LuaFrame::className[] = "Frame";
    const char* LuaFrame::classList[] = {"Frame",
        "Button", "CheckButton", "EditBox", "MessageFrame", "ScrollFrame",
        "ScrollingMessageFrame", "Slider", "StatusBar", 0
    };
    Lunar<LuaFrame>::RegType LuaFrame::methods[] = {
        {"dt", &LuaFrame::GetDataTable},

        // UIObject (inherited)
        method(Frame, GetAlpha),
        method(Frame, GetName),
        method(Frame, GetObjectType),
        method(Frame, IsObjectType),
        method(Frame, SetAlpha),

        method(Frame, ClearAllPoints),
        method(Frame, GetBase),
        method(Frame, GetBottom),
        method(Frame, GetCenter),
        method(Frame, GetHeight),
        method(Frame, GetLeft),
        method(Frame, GetNumPoint),
        method(Frame, GetParent),
        method(Frame, GetPoint),
        method(Frame, GetRight),
        method(Frame, GetTop),
        method(Frame, GetWidth),
        method(Frame, Hide),
        method(Frame, IsShown),
        method(Frame, IsVisible),
        method(Frame, SetAllPoints),
        method(Frame, SetHeight),
        method(Frame, SetParent),
        method(Frame, SetPoint),
        method(Frame, SetRelPoint),
        method(Frame, SetWidth),
        method(Frame, Show),

        // Frame
        method(Frame, CreateFontString),
        method(Frame, CreateTexture),
        method(Frame, CreateTitleRegion),
        method(Frame, DisableDrawLayer),
        method(Frame, EnableDrawLayer),
        method(Frame, EnableKeyboard),
        method(Frame, EnableMouse),
        method(Frame, EnableMouseWheel),
        method(Frame, GetBackdrop),
        method(Frame, GetBackdropBorderColor),
        method(Frame, GetBackdropColor),
        method(Frame, GetChildren),
        method(Frame, GetEffectiveAlpha),
        method(Frame, GetEffectiveScale),
        method(Frame, GetFrameLevel),
        method(Frame, GetFrameStrata),
        method(Frame, GetFrameType),
        method(Frame, GetHitRectInsets),
        method(Frame, GetID),
        method(Frame, GetMaxResize),
        method(Frame, GetMinResize),
        method(Frame, SetMaxWidth),
        method(Frame, SetMaxHeight),
        method(Frame, SetMinWidth),
        method(Frame, SetMinHeight),
        method(Frame, GetNumChildren),
        method(Frame, GetNumRegions),
        method(Frame, GetScale),
        method(Frame, GetScript),
        method(Frame, GetTitleRegion),
        method(Frame, HasScript),
        method(Frame, IsClampedToScreen),
        method(Frame, IsFrameType),
        method(Frame, IsKeyboardEnabled),
        method(Frame, IsMouseEnabled),
        method(Frame, IsMouseWheelEnabled),
        method(Frame, IsMovable),
        method(Frame, IsResizable),
        method(Frame, IsTopLevel),
        method(Frame, IsUserPlaced),
        method(Frame, Lower),
        method(Frame, On),
        method(Frame, Raise),
        method(Frame, RegisterAllEvents),
        method(Frame, RegisterEvent),
        method(Frame, RegisterForDrag),
        method(Frame, SetBackdrop),
        method(Frame, SetBackdropBorderColor),
        method(Frame, SetBackdropColor),
        method(Frame, SetClampedToScreen),
        method(Frame, SetFrameStrata),
        method(Frame, SetHitRectInsets),
        method(Frame, SetMaxResize),
        method(Frame, SetMinResize),
        method(Frame, SetMovable),
        method(Frame, SetResizable),
        method(Frame, SetScale),
        method(Frame, SetScript),
        method(Frame, SetTopLevel),
        method(Frame, SetUserPlaced),
        method(Frame, StartMoving),
        method(Frame, StartSizing),
        method(Frame, StopMovingOrSizing),
        method(Frame, UnregisterAllEvents),
        method(Frame, UnregisterEvent),

        {0,0}
    };

    const char  LuaCheckButton::className[] = "CheckButton";
    const char* LuaCheckButton::classList[] = {"CheckButton", 0};
    Lunar<LuaCheckButton>::RegType LuaCheckButton::methods[] = {
        {"dt", &LuaCheckButton::GetDataTable},

        // UIObject (inherited)
        method(CheckButton, GetAlpha),
        method(CheckButton, GetName),
        method(CheckButton, GetObjectType),
        method(CheckButton, IsObjectType),
        method(CheckButton, SetAlpha),

        method(CheckButton, ClearAllPoints),
        method(CheckButton, GetBase),
        method(CheckButton, GetBottom),
        method(CheckButton, GetCenter),
        method(CheckButton, GetHeight),
        method(CheckButton, GetLeft),
        method(CheckButton, GetNumPoint),
        method(CheckButton, GetParent),
        method(CheckButton, GetPoint),
        method(CheckButton, GetRight),
        method(CheckButton, GetTop),
        method(CheckButton, GetWidth),
        method(CheckButton, Hide),
        method(CheckButton, IsShown),
        method(CheckButton, IsVisible),
        method(CheckButton, SetAllPoints),
        method(CheckButton, SetHeight),
        method(CheckButton, SetParent),
        method(CheckButton, SetPoint),
        method(CheckButton, SetRelPoint),
        method(CheckButton, SetWidth),
        method(CheckButton, Show),

        // Frame (inherited)
        method(CheckButton, CreateFontString),
        method(CheckButton, CreateTexture),
        method(CheckButton, CreateTitleRegion),
        method(CheckButton, DisableDrawLayer),
        method(CheckButton, EnableDrawLayer),
        method(CheckButton, EnableKeyboard),
        method(CheckButton, EnableMouse),
        method(CheckButton, EnableMouseWheel),
        method(CheckButton, GetBackdrop),
        method(CheckButton, GetBackdropBorderColor),
        method(CheckButton, GetBackdropColor),
        method(CheckButton, GetChildren),
        method(CheckButton, GetEffectiveAlpha),
        method(CheckButton, GetEffectiveScale),
        method(CheckButton, GetFrameLevel),
        method(CheckButton, GetFrameStrata),
        method(CheckButton, GetFrameType),
        method(CheckButton, GetHitRectInsets),
        method(CheckButton, GetID),
        method(CheckButton, GetMaxResize),
        method(CheckButton, GetMinResize),
        method(CheckButton, SetMaxWidth),
        method(CheckButton, SetMaxHeight),
        method(CheckButton, SetMinWidth),
        method(CheckButton, SetMinHeight),
        method(CheckButton, GetNumChildren),
        method(CheckButton, GetNumRegions),
        method(CheckButton, GetScale),
        method(CheckButton, GetScript),
        method(CheckButton, GetTitleRegion),
        method(CheckButton, HasScript),
        method(CheckButton, IsClampedToScreen),
        method(CheckButton, IsFrameType),
        method(CheckButton, IsKeyboardEnabled),
        method(CheckButton, IsMouseEnabled),
        method(CheckButton, IsMouseWheelEnabled),
        method(CheckButton, IsMovable),
        method(CheckButton, IsResizable),
        method(CheckButton, IsTopLevel),
        method(CheckButton, IsUserPlaced),
        method(CheckButton, Lower),
        method(CheckButton, On),
        method(CheckButton, Raise),
        method(CheckButton, RegisterAllEvents),
        method(CheckButton, RegisterEvent),
        method(CheckButton, RegisterForDrag),
        method(CheckButton, SetBackdrop),
        method(CheckButton, SetBackdropBorderColor),
        method(CheckButton, SetBackdropColor),
        method(CheckButton, SetClampedToScreen),
        method(CheckButton, SetFrameStrata),
        method(CheckButton, SetHitRectInsets),
        method(CheckButton, SetMaxResize),
        method(CheckButton, SetMinResize),
        method(CheckButton, SetMovable),
        method(CheckButton, SetResizable),
        method(CheckButton, SetScale),
        method(CheckButton, SetScript),
        method(CheckButton, SetTopLevel),
        method(CheckButton, SetUserPlaced),
        method(CheckButton, StartMoving),
        method(CheckButton, StartSizing),
        method(CheckButton, StopMovingOrSizing),
        method(CheckButton, UnregisterAllEvents),
        method(CheckButton, UnregisterEvent),

        // Button (inherited)
        method(CheckButton, Click),
        method(CheckButton, Disable),
        method(CheckButton, Enable),
        method(CheckButton, GetButtonState),
        method(CheckButton, GetDisabledFontObject),
        method(CheckButton, GetDisabledTextColor),
        method(CheckButton, GetDisabledTexture),
        method(CheckButton, GetHighlightFontObject),
        method(CheckButton, GetHighlightTextColor),
        method(CheckButton, GetHighlightTexture),
        method(CheckButton, GetNormalFontObject),
        method(CheckButton, GetNormalTexture),
        method(CheckButton, GetPushedTextOffset),
        method(CheckButton, GetPushedTexture),
        method(CheckButton, GetText),
        method(CheckButton, GetTextHeight),
        method(CheckButton, GetTextWidth),
        method(CheckButton, IsEnabled),
        method(CheckButton, LockHighlight),
        method(CheckButton, RegisterForClicks),
        method(CheckButton, SetButtonState),
        method(CheckButton, SetDisabledFontObject),
        method(CheckButton, SetDisabledTextColor),
        method(CheckButton, SetDisabledTexture),
        method(CheckButton, SetHighlightFontObject),
        method(CheckButton, SetHighlightTextColor),
        method(CheckButton, SetHighlightTexture),
        method(CheckButton, SetNormalFontObject),
        method(CheckButton, SetNormalTextColor),
        method(CheckButton, SetNormalTexture),
        method(CheckButton, SetPushedTextOffset),
        method(CheckButton, SetPushedTexture),
        method(CheckButton, SetText),
        method(CheckButton, UnlockHighlight),

        // CheckButton
        method(CheckButton, IsChecked),
        method(CheckButton, GetCheckedTexture),
        method(CheckButton, GetDisabledCheckedTexture),
        method(CheckButton, SetChecked),
        method(CheckButton, SetCheckedTexture),
        method(CheckButton, SetDisabledCheckedTexture),

        {0,0}
    };

    const char  LuaStatusBar::className[] = "StatusBar";
    const char* LuaStatusBar::classList[] = {"StatusBar", 0};
    Lunar<LuaStatusBar>::RegType LuaStatusBar::methods[] = {
        {"dt", &LuaStatusBar::GetDataTable},

        // UIObject (inherited)
        method(StatusBar, GetAlpha),
        method(StatusBar, GetName),
        method(StatusBar, GetObjectType),
        method(StatusBar, IsObjectType),
        method(StatusBar, SetAlpha),

        method(StatusBar, ClearAllPoints),
        method(StatusBar, GetBase),
        method(StatusBar, GetBottom),
        method(StatusBar, GetCenter),
        method(StatusBar, GetHeight),
        method(StatusBar, GetLeft),
        method(StatusBar, GetNumPoint),
        method(StatusBar, GetParent),
        method(StatusBar, GetPoint),
        method(StatusBar, GetRight),
        method(StatusBar, GetTop),
        method(StatusBar, GetWidth),
        method(StatusBar, Hide),
        method(StatusBar, IsShown),
        method(StatusBar, IsVisible),
        method(StatusBar, SetAllPoints),
        method(StatusBar, SetHeight),
        method(StatusBar, SetParent),
        method(StatusBar, SetPoint),
        method(StatusBar, SetRelPoint),
        method(StatusBar, SetWidth),
        method(StatusBar, Show),

        // Frame (inherited)
        method(StatusBar, CreateFontString),
        method(StatusBar, CreateTexture),
        method(StatusBar, CreateTitleRegion),
        method(StatusBar, DisableDrawLayer),
        method(StatusBar, EnableDrawLayer),
        method(StatusBar, EnableKeyboard),
        method(StatusBar, EnableMouse),
        method(StatusBar, EnableMouseWheel),
        method(StatusBar, GetBackdrop),
        method(StatusBar, GetBackdropBorderColor),
        method(StatusBar, GetBackdropColor),
        method(StatusBar, GetChildren),
        method(StatusBar, GetEffectiveAlpha),
        method(StatusBar, GetEffectiveScale),
        method(StatusBar, GetFrameLevel),
        method(StatusBar, GetFrameStrata),
        method(StatusBar, GetFrameType),
        method(StatusBar, GetHitRectInsets),
        method(StatusBar, GetID),
        method(StatusBar, GetMaxResize),
        method(StatusBar, GetMinResize),
        method(StatusBar, SetMaxWidth),
        method(StatusBar, SetMaxHeight),
        method(StatusBar, SetMinWidth),
        method(StatusBar, SetMinHeight),
        method(StatusBar, GetNumChildren),
        method(StatusBar, GetNumRegions),
        method(StatusBar, GetScale),
        method(StatusBar, GetScript),
        method(StatusBar, GetTitleRegion),
        method(StatusBar, HasScript),
        method(StatusBar, IsClampedToScreen),
        method(StatusBar, IsFrameType),
        method(StatusBar, IsKeyboardEnabled),
        method(StatusBar, IsMouseEnabled),
        method(StatusBar, IsMouseWheelEnabled),
        method(StatusBar, IsMovable),
        method(StatusBar, IsResizable),
        method(StatusBar, IsTopLevel),
        method(StatusBar, IsUserPlaced),
        method(StatusBar, Lower),
        method(StatusBar, On),
        method(StatusBar, Raise),
        method(StatusBar, RegisterAllEvents),
        method(StatusBar, RegisterEvent),
        method(StatusBar, RegisterForDrag),
        method(StatusBar, SetBackdrop),
        method(StatusBar, SetBackdropBorderColor),
        method(StatusBar, SetBackdropColor),
        method(StatusBar, SetClampedToScreen),
        method(StatusBar, SetFrameStrata),
        method(StatusBar, SetHitRectInsets),
        method(StatusBar, SetMaxResize),
        method(StatusBar, SetMinResize),
        method(StatusBar, SetMovable),
        method(StatusBar, SetResizable),
        method(StatusBar, SetScale),
        method(StatusBar, SetScript),
        method(StatusBar, SetTopLevel),
        method(StatusBar, SetUserPlaced),
        method(StatusBar, StartMoving),
        method(StatusBar, StartSizing),
        method(StatusBar, StopMovingOrSizing),
        method(StatusBar, UnregisterAllEvents),
        method(StatusBar, UnregisterEvent),

        // StatusBar
        method(StatusBar, GetMinMaxValues),
        method(StatusBar, GetOrientation),
        method(StatusBar, GetStatusBarColor),
        method(StatusBar, GetStatusBarTexture),
        method(StatusBar, GetValue),
        method(StatusBar, SetMinMaxValues),
        method(StatusBar, SetOrientation),
        method(StatusBar, SetStatusBarColor),
        method(StatusBar, SetStatusBarTexture),
        method(StatusBar, SetValue),

        {0,0}
    };

    const char  LuaEditBox::className[] = "EditBox";
    const char* LuaEditBox::classList[] = {"EditBox", 0};
    Lunar<LuaEditBox>::RegType LuaEditBox::methods[] = {
        {"dt", &LuaEditBox::GetDataTable},

        // UIObject (inherited)
        method(EditBox, GetAlpha),
        method(EditBox, GetName),
        method(EditBox, GetObjectType),
        method(EditBox, IsObjectType),
        method(EditBox, SetAlpha),

        method(EditBox, ClearAllPoints),
        method(EditBox, GetBase),
        method(EditBox, GetBottom),
        method(EditBox, GetCenter),
        method(EditBox, GetHeight),
        method(EditBox, GetLeft),
        method(EditBox, GetNumPoint),
        method(EditBox, GetParent),
        method(EditBox, GetPoint),
        method(EditBox, GetRight),
        method(EditBox, GetTop),
        method(EditBox, GetWidth),
        method(EditBox, Hide),
        method(EditBox, IsShown),
        method(EditBox, IsVisible),
        method(EditBox, SetAllPoints),
        method(EditBox, SetHeight),
        method(EditBox, SetParent),
        method(EditBox, SetPoint),
        method(EditBox, SetRelPoint),
        method(EditBox, SetWidth),
        method(EditBox, Show),

        // Frame (inherited)
        method(EditBox, CreateFontString),
        method(EditBox, CreateTexture),
        method(EditBox, CreateTitleRegion),
        method(EditBox, DisableDrawLayer),
        method(EditBox, EnableDrawLayer),
        method(EditBox, EnableKeyboard),
        method(EditBox, EnableMouse),
        method(EditBox, EnableMouseWheel),
        method(EditBox, GetBackdrop),
        method(EditBox, GetBackdropBorderColor),
        method(EditBox, GetBackdropColor),
        method(EditBox, GetChildren),
        method(EditBox, GetEffectiveAlpha),
        method(EditBox, GetEffectiveScale),
        method(EditBox, GetFrameLevel),
        method(EditBox, GetFrameStrata),
        method(EditBox, GetFrameType),
        method(EditBox, GetHitRectInsets),
        method(EditBox, GetID),
        method(EditBox, GetMaxResize),
        method(EditBox, GetMinResize),
        method(EditBox, SetMaxWidth),
        method(EditBox, SetMaxHeight),
        method(EditBox, SetMinWidth),
        method(EditBox, SetMinHeight),
        method(EditBox, GetNumChildren),
        method(EditBox, GetNumRegions),
        method(EditBox, GetScale),
        method(EditBox, GetScript),
        method(EditBox, GetTitleRegion),
        method(EditBox, HasScript),
        method(EditBox, IsClampedToScreen),
        method(EditBox, IsFrameType),
        method(EditBox, IsKeyboardEnabled),
        method(EditBox, IsMouseEnabled),
        method(EditBox, IsMouseWheelEnabled),
        method(EditBox, IsMovable),
        method(EditBox, IsResizable),
        method(EditBox, IsTopLevel),
        method(EditBox, IsUserPlaced),
        method(EditBox, Lower),
        method(EditBox, On),
        method(EditBox, Raise),
        method(EditBox, RegisterAllEvents),
        method(EditBox, RegisterEvent),
        method(EditBox, RegisterForDrag),
        method(EditBox, SetBackdrop),
        method(EditBox, SetBackdropBorderColor),
        method(EditBox, SetBackdropColor),
        method(EditBox, SetClampedToScreen),
        method(EditBox, SetFrameStrata),
        method(EditBox, SetHitRectInsets),
        method(EditBox, SetMaxResize),
        method(EditBox, SetMinResize),
        method(EditBox, SetMovable),
        method(EditBox, SetResizable),
        method(EditBox, SetScale),
        method(EditBox, SetScript),
        method(EditBox, SetTopLevel),
        method(EditBox, SetUserPlaced),
        method(EditBox, StartMoving),
        method(EditBox, StartSizing),
        method(EditBox, StopMovingOrSizing),
        method(EditBox, UnregisterAllEvents),
        method(EditBox, UnregisterEvent),

        // EditBox
        method(EditBox, AddHistoryLine),
        method(EditBox, ClearFocus),
        method(EditBox, GetBlinkSpeed),
        method(EditBox, GetHistoryLines),
        method(EditBox, GetMaxLetters),
        method(EditBox, GetNumLetters),
        method(EditBox, GetNumber),
        method(EditBox, GetText),
        method(EditBox, GetTextInsets),
        method(EditBox, HighlithtText),
        method(EditBox, Insert),
        method(EditBox, IsAutoFocus),
        method(EditBox, IsMultiLine),
        method(EditBox, IsNumeric),
        method(EditBox, IsPassword),
        method(EditBox, SetAutoFocus),
        method(EditBox, SetBlinkSpeed),
        method(EditBox, SetFocus),
        method(EditBox, SetMaxHistoryLines),
        method(EditBox, SetMaxLetters),
        method(EditBox, SetMultiLine),
        method(EditBox, SetNumber),
        method(EditBox, SetNumeric),
        method(EditBox, SetPassword),
        method(EditBox, SetText),
        method(EditBox, SetTextInsets),

        {0,0}
    };

    const char  LuaMessageFrame::className[] = "MessageFrame";
    const char* LuaMessageFrame::classList[] = {"MessageFrame", 0};
    Lunar<LuaMessageFrame>::RegType LuaMessageFrame::methods[] = {
        {"dt", &LuaMessageFrame::GetDataTable},
        {0,0}
    };

    const char  LuaScrollFrame::className[] = "ScrollFrame";
    const char* LuaScrollFrame::classList[] = {"ScrollFrame", 0};
    Lunar<LuaScrollFrame>::RegType LuaScrollFrame::methods[] = {
        {"dt", &LuaScrollFrame::GetDataTable},

        // UIObject (inherited)
        method(ScrollFrame, GetAlpha),
        method(ScrollFrame, GetName),
        method(ScrollFrame, GetObjectType),
        method(ScrollFrame, IsObjectType),
        method(ScrollFrame, SetAlpha),

        method(ScrollFrame, ClearAllPoints),
        method(ScrollFrame, GetBase),
        method(ScrollFrame, GetBottom),
        method(ScrollFrame, GetCenter),
        method(ScrollFrame, GetHeight),
        method(ScrollFrame, GetLeft),
        method(ScrollFrame, GetNumPoint),
        method(ScrollFrame, GetParent),
        method(ScrollFrame, GetPoint),
        method(ScrollFrame, GetRight),
        method(ScrollFrame, GetTop),
        method(ScrollFrame, GetWidth),
        method(ScrollFrame, Hide),
        method(ScrollFrame, IsShown),
        method(ScrollFrame, IsVisible),
        method(ScrollFrame, SetAllPoints),
        method(ScrollFrame, SetHeight),
        method(ScrollFrame, SetParent),
        method(ScrollFrame, SetPoint),
        method(ScrollFrame, SetRelPoint),
        method(ScrollFrame, SetWidth),
        method(ScrollFrame, Show),

        // Frame (inherited)
        method(ScrollFrame, CreateFontString),
        method(ScrollFrame, CreateTexture),
        method(ScrollFrame, CreateTitleRegion),
        method(ScrollFrame, DisableDrawLayer),
        method(ScrollFrame, EnableDrawLayer),
        method(ScrollFrame, EnableKeyboard),
        method(ScrollFrame, EnableMouse),
        method(ScrollFrame, EnableMouseWheel),
        method(ScrollFrame, GetBackdrop),
        method(ScrollFrame, GetBackdropBorderColor),
        method(ScrollFrame, GetBackdropColor),
        method(ScrollFrame, GetChildren),
        method(ScrollFrame, GetEffectiveAlpha),
        method(ScrollFrame, GetEffectiveScale),
        method(ScrollFrame, GetFrameLevel),
        method(ScrollFrame, GetFrameStrata),
        method(ScrollFrame, GetFrameType),
        method(ScrollFrame, GetHitRectInsets),
        method(ScrollFrame, GetID),
        method(ScrollFrame, GetMaxResize),
        method(ScrollFrame, GetMinResize),
        method(ScrollFrame, SetMaxWidth),
        method(ScrollFrame, SetMaxHeight),
        method(ScrollFrame, SetMinWidth),
        method(ScrollFrame, SetMinHeight),
        method(ScrollFrame, GetNumChildren),
        method(ScrollFrame, GetNumRegions),
        method(ScrollFrame, GetScale),
        method(ScrollFrame, GetScript),
        method(ScrollFrame, GetTitleRegion),
        method(ScrollFrame, HasScript),
        method(ScrollFrame, IsClampedToScreen),
        method(ScrollFrame, IsFrameType),
        method(ScrollFrame, IsKeyboardEnabled),
        method(ScrollFrame, IsMouseEnabled),
        method(ScrollFrame, IsMouseWheelEnabled),
        method(ScrollFrame, IsMovable),
        method(ScrollFrame, IsResizable),
        method(ScrollFrame, IsTopLevel),
        method(ScrollFrame, IsUserPlaced),
        method(ScrollFrame, Lower),
        method(ScrollFrame, On),
        method(ScrollFrame, Raise),
        method(ScrollFrame, RegisterAllEvents),
        method(ScrollFrame, RegisterEvent),
        method(ScrollFrame, RegisterForDrag),
        method(ScrollFrame, SetBackdrop),
        method(ScrollFrame, SetBackdropBorderColor),
        method(ScrollFrame, SetBackdropColor),
        method(ScrollFrame, SetClampedToScreen),
        method(ScrollFrame, SetFrameStrata),
        method(ScrollFrame, SetHitRectInsets),
        method(ScrollFrame, SetMaxResize),
        method(ScrollFrame, SetMinResize),
        method(ScrollFrame, SetMovable),
        method(ScrollFrame, SetResizable),
        method(ScrollFrame, SetScale),
        method(ScrollFrame, SetScript),
        method(ScrollFrame, SetTopLevel),
        method(ScrollFrame, SetUserPlaced),
        method(ScrollFrame, StartMoving),
        method(ScrollFrame, StartSizing),
        method(ScrollFrame, StopMovingOrSizing),
        method(ScrollFrame, UnregisterAllEvents),
        method(ScrollFrame, UnregisterEvent),

        // ScrollFrame
        method(ScrollFrame, GetHorizontalScroll),
        method(ScrollFrame, GetHorizontalScrollRange),
        method(ScrollFrame, GetScrollChild),
        method(ScrollFrame, GetVerticalScroll),
        method(ScrollFrame, GetVerticalScrollRange),
        method(ScrollFrame, SetHorizontalScroll),
        method(ScrollFrame, SetScrollChild),
        method(ScrollFrame, SetVerticalScroll),

        {0,0}
    };

    const char  LuaScrollingMessageFrame::className[] = "ScrollingMessageFrame";
    const char* LuaScrollingMessageFrame::classList[] = {"ScrollingMessageFrame", 0};
    Lunar<LuaScrollingMessageFrame>::RegType LuaScrollingMessageFrame::methods[] = {
        {"dt", &LuaScrollingMessageFrame::GetDataTable},
        {0,0}
    };

    const char  LuaButton::className[] = "Button";
    const char* LuaButton::classList[] = {"Button", "CheckButton", 0};
    Lunar<LuaButton>::RegType LuaButton::methods[] = {
        {"dt", &LuaButton::GetDataTable},

        // UIObject (inherited)
        method(Button, GetAlpha),
        method(Button, GetName),
        method(Button, GetObjectType),
        method(Button, IsObjectType),
        method(Button, SetAlpha),

        method(Button, ClearAllPoints),
        method(Button, GetBase),
        method(Button, GetBottom),
        method(Button, GetCenter),
        method(Button, GetHeight),
        method(Button, GetLeft),
        method(Button, GetNumPoint),
        method(Button, GetParent),
        method(Button, GetPoint),
        method(Button, GetRight),
        method(Button, GetTop),
        method(Button, GetWidth),
        method(Button, Hide),
        method(Button, IsShown),
        method(Button, IsVisible),
        method(Button, SetAllPoints),
        method(Button, SetHeight),
        method(Button, SetParent),
        method(Button, SetPoint),
        method(Button, SetRelPoint),
        method(Button, SetWidth),
        method(Button, Show),

        // Frame (inherited)
        method(Button, CreateFontString),
        method(Button, CreateTexture),
        method(Button, CreateTitleRegion),
        method(Button, DisableDrawLayer),
        method(Button, EnableDrawLayer),
        method(Button, EnableKeyboard),
        method(Button, EnableMouse),
        method(Button, EnableMouseWheel),
        method(Button, GetBackdrop),
        method(Button, GetBackdropBorderColor),
        method(Button, GetBackdropColor),
        method(Button, GetChildren),
        method(Button, GetEffectiveAlpha),
        method(Button, GetEffectiveScale),
        method(Button, GetFrameLevel),
        method(Button, GetFrameStrata),
        method(Button, GetFrameType),
        method(Button, GetHitRectInsets),
        method(Button, GetID),
        method(Button, GetMaxResize),
        method(Button, GetMinResize),
        method(Button, SetMaxWidth),
        method(Button, SetMaxHeight),
        method(Button, SetMinWidth),
        method(Button, SetMinHeight),
        method(Button, GetNumChildren),
        method(Button, GetNumRegions),
        method(Button, GetScale),
        method(Button, GetScript),
        method(Button, GetTitleRegion),
        method(Button, HasScript),
        method(Button, IsClampedToScreen),
        method(Button, IsFrameType),
        method(Button, IsKeyboardEnabled),
        method(Button, IsMouseEnabled),
        method(Button, IsMouseWheelEnabled),
        method(Button, IsMovable),
        method(Button, IsResizable),
        method(Button, IsTopLevel),
        method(Button, IsUserPlaced),
        method(Button, Lower),
        method(Button, On),
        method(Button, Raise),
        method(Button, RegisterAllEvents),
        method(Button, RegisterEvent),
        method(Button, RegisterForDrag),
        method(Button, SetBackdrop),
        method(Button, SetBackdropBorderColor),
        method(Button, SetBackdropColor),
        method(Button, SetClampedToScreen),
        method(Button, SetFrameStrata),
        method(Button, SetHitRectInsets),
        method(Button, SetMaxResize),
        method(Button, SetMinResize),
        method(Button, SetMovable),
        method(Button, SetResizable),
        method(Button, SetScale),
        method(Button, SetScript),
        method(Button, SetTopLevel),
        method(Button, SetUserPlaced),
        method(Button, StartMoving),
        method(Button, StartSizing),
        method(Button, StopMovingOrSizing),
        method(Button, UnregisterAllEvents),
        method(Button, UnregisterEvent),

        // Button
        method(Button, Click),
        method(Button, Disable),
        method(Button, Enable),
        method(Button, GetButtonState),
        method(Button, GetDisabledFontObject),
        method(Button, GetDisabledTextColor),
        method(Button, GetDisabledTexture),
        method(Button, GetHighlightFontObject),
        method(Button, GetHighlightTextColor),
        method(Button, GetHighlightTexture),
        method(Button, GetNormalFontObject),
        method(Button, GetNormalTexture),
        method(Button, GetPushedTextOffset),
        method(Button, GetPushedTexture),
        method(Button, GetText),
        method(Button, GetTextHeight),
        method(Button, GetTextWidth),
        method(Button, IsEnabled),
        method(Button, LockHighlight),
        method(Button, RegisterForClicks),
        method(Button, SetButtonState),
        method(Button, SetDisabledFontObject),
        method(Button, SetDisabledTextColor),
        method(Button, SetDisabledTexture),
        method(Button, SetHighlightFontObject),
        method(Button, SetHighlightTextColor),
        method(Button, SetHighlightTexture),
        method(Button, SetNormalFontObject),
        method(Button, SetNormalTextColor),
        method(Button, SetNormalTexture),
        method(Button, SetPushedTextOffset),
        method(Button, SetPushedTexture),
        method(Button, SetText),
        method(Button, UnlockHighlight),

        {0,0}
    };

    const char  LuaSlider::className[] = "Slider";
    const char* LuaSlider::classList[] = {"Slider", 0};
    Lunar<LuaSlider>::RegType LuaSlider::methods[] = {
        {"dt", &LuaSlider::GetDataTable},

        // UIObject (inherited)
        method(Slider, GetAlpha),
        method(Slider, GetName),
        method(Slider, GetObjectType),
        method(Slider, IsObjectType),
        method(Slider, SetAlpha),

        method(Slider, ClearAllPoints),
        method(Slider, GetBase),
        method(Slider, GetBottom),
        method(Slider, GetCenter),
        method(Slider, GetHeight),
        method(Slider, GetLeft),
        method(Slider, GetNumPoint),
        method(Slider, GetParent),
        method(Slider, GetPoint),
        method(Slider, GetRight),
        method(Slider, GetTop),
        method(Slider, GetWidth),
        method(Slider, Hide),
        method(Slider, IsShown),
        method(Slider, IsVisible),
        method(Slider, SetAllPoints),
        method(Slider, SetHeight),
        method(Slider, SetParent),
        method(Slider, SetPoint),
        method(Slider, SetRelPoint),
        method(Slider, SetWidth),
        method(Slider, Show),

        // Frame (inherited)
        method(Slider, CreateFontString),
        method(Slider, CreateTexture),
        method(Slider, CreateTitleRegion),
        method(Slider, DisableDrawLayer),
        method(Slider, EnableDrawLayer),
        method(Slider, EnableKeyboard),
        method(Slider, EnableMouse),
        method(Slider, EnableMouseWheel),
        method(Slider, GetBackdrop),
        method(Slider, GetBackdropBorderColor),
        method(Slider, GetBackdropColor),
        method(Slider, GetChildren),
        method(Slider, GetEffectiveAlpha),
        method(Slider, GetEffectiveScale),
        method(Slider, GetFrameLevel),
        method(Slider, GetFrameStrata),
        method(Slider, GetFrameType),
        method(Slider, GetHitRectInsets),
        method(Slider, GetID),
        method(Slider, GetMaxResize),
        method(Slider, GetMinResize),
        method(Slider, SetMaxWidth),
        method(Slider, SetMaxHeight),
        method(Slider, SetMinWidth),
        method(Slider, SetMinHeight),
        method(Slider, GetNumChildren),
        method(Slider, GetNumRegions),
        method(Slider, GetScale),
        method(Slider, GetScript),
        method(Slider, GetTitleRegion),
        method(Slider, HasScript),
        method(Slider, IsClampedToScreen),
        method(Slider, IsFrameType),
        method(Slider, IsKeyboardEnabled),
        method(Slider, IsMouseEnabled),
        method(Slider, IsMouseWheelEnabled),
        method(Slider, IsMovable),
        method(Slider, IsResizable),
        method(Slider, IsTopLevel),
        method(Slider, IsUserPlaced),
        method(Slider, Lower),
        method(Slider, On),
        method(Slider, Raise),
        method(Slider, RegisterAllEvents),
        method(Slider, RegisterEvent),
        method(Slider, RegisterForDrag),
        method(Slider, SetBackdrop),
        method(Slider, SetBackdropBorderColor),
        method(Slider, SetBackdropColor),
        method(Slider, SetClampedToScreen),
        method(Slider, SetFrameStrata),
        method(Slider, SetHitRectInsets),
        method(Slider, SetMaxResize),
        method(Slider, SetMinResize),
        method(Slider, SetMovable),
        method(Slider, SetResizable),
        method(Slider, SetScale),
        method(Slider, SetScript),
        method(Slider, SetTopLevel),
        method(Slider, SetUserPlaced),
        method(Slider, StartMoving),
        method(Slider, StartSizing),
        method(Slider, StopMovingOrSizing),
        method(Slider, UnregisterAllEvents),
        method(Slider, UnregisterEvent),

        // StatusBar
        method(Slider, AllowClicksOutsideThumb),
        method(Slider, GetMaxValue),
        method(Slider, GetMinValue),
        method(Slider, GetMinMaxValues),
        method(Slider, GetOrientation),
        method(Slider, GetThumbTexture),
        method(Slider, GetValue),
        method(Slider, GetValueStep),
        method(Slider, SetMaxValue),
        method(Slider, SetMinValue),
        method(Slider, SetMinMaxValues),
        method(Slider, SetOrientation),
        method(Slider, SetThumbTexture),
        method(Slider, SetValue),
        method(Slider, SetValueStep),

        {0,0}
    };

    const char  LuaLayeredRegion::className[] = "LayeredRegion";
    const char* LuaLayeredRegion::classList[] = {"LayeredRegion",
        "Texture", "FontString", 0
    };
    Lunar<LuaLayeredRegion>::RegType LuaLayeredRegion::methods[] = {
        {"dt", &LuaLayeredRegion::GetDataTable},
        {0,0}
    };

    const char  LuaTexture::className[] = "Texture";
    const char* LuaTexture::classList[] = {"Texture", 0};
    Lunar<LuaTexture>::RegType LuaTexture::methods[] = {
        {"dt", &LuaTexture::GetDataTable},

        // UIObject (inherited)
        method(Texture, GetAlpha),
        method(Texture, GetName),
        method(Texture, GetObjectType),
        method(Texture, IsObjectType),
        method(Texture, SetAlpha),

        method(Texture, ClearAllPoints),
        method(Texture, GetBase),
        method(Texture, GetBottom),
        method(Texture, GetCenter),
        method(Texture, GetHeight),
        method(Texture, GetLeft),
        method(Texture, GetNumPoint),
        method(Texture, GetParent),
        method(Texture, GetPoint),
        method(Texture, GetRight),
        method(Texture, GetTop),
        method(Texture, GetWidth),
        method(Texture, Hide),
        method(Texture, IsShown),
        method(Texture, IsVisible),
        method(Texture, SetAllPoints),
        method(Texture, SetHeight),
        method(Texture, SetParent),
        method(Texture, SetPoint),
        method(Texture, SetRelPoint),
        method(Texture, SetWidth),
        method(Texture, Show),

        // LayeredRegion (inherited)
        method(Texture, GetDrawLayer),
        method(Texture, SetDrawLayer),

        // Texture
        method(Texture, GetBlendMode),
        method(Texture, GetTexCoord),
        method(Texture, GetTexCoordModifiesRect),
        method(Texture, GetTexture),
        method(Texture, GetVertexColor),
        method(Texture, IsDesaturated),
        method(Texture, SetBlendMode),
        method(Texture, SetDesaturated),
        method(Texture, SetGradient),
        method(Texture, SetGradientAlpha),
        method(Texture, SetTexCoord),
        method(Texture, SetTexCoordModifiesRect),
        method(Texture, SetTexture),
        method(Texture, SetVertexColor),

        {0,0}
    };

    const char  LuaFontString::className[] = "FontString";
    const char* LuaFontString::classList[] = {"FontString", 0};
    Lunar<LuaFontString>::RegType LuaFontString::methods[] = {
        {"dt", &LuaFontString::GetDataTable},

        // UIObject (inherited)
        method(FontString, GetAlpha),
        method(FontString, GetName),
        method(FontString, GetObjectType),
        method(FontString, IsObjectType),
        method(FontString, SetAlpha),

        method(FontString, ClearAllPoints),
        method(FontString, GetBase),
        method(FontString, GetBottom),
        method(FontString, GetCenter),
        method(FontString, GetHeight),
        method(FontString, GetLeft),
        method(FontString, GetNumPoint),
        method(FontString, GetParent),
        method(FontString, GetPoint),
        method(FontString, GetRight),
        method(FontString, GetTop),
        method(FontString, GetWidth),
        method(FontString, Hide),
        method(FontString, IsShown),
        method(FontString, IsVisible),
        method(FontString, SetAllPoints),
        method(FontString, SetHeight),
        method(FontString, SetParent),
        method(FontString, SetPoint),
        method(FontString, SetRelPoint),
        method(FontString, SetWidth),
        method(FontString, Show),

        // LayeredRegion (inherited)
        method(FontString, GetDrawLayer),
        method(FontString, SetDrawLayer),

        // FontInstance
        method(FontString, GetFont),
        method(FontString, GetFontObject),
        method(FontString, GetJustifyH),
        method(FontString, GetJustifyV),
        method(FontString, GetShadowColor),
        method(FontString, GetShadowOffset),
        method(FontString, GetSpacing),
        method(FontString, GetTextColor),
        method(FontString, SetFont),
        method(FontString, SetFontObject),
        method(FontString, SetJustifyH),
        method(FontString, SetJustifyV),
        method(FontString, SetShadowColor),
        method(FontString, SetShadowOffset),
        method(FontString, SetSpacing),
        method(FontString, SetTextColor),

        // FontString
        method(FontString, CanNonSpaceWrap),
        method(FontString, CanWordWrap),
        method(FontString, EnableFormatting),
        method(FontString, GetStringHeight),
        method(FontString, GetStringWidth),
        method(FontString, GetText),
        method(FontString, IsFormattingEnabled),
        method(FontString, SetAlphaGradient),
        method(FontString, SetNonSpaceWrap),
        method(FontString, SetText),
        method(FontString, SetTextHeight),
        method(FontString, SetWordWrap),

        {0,0}
    };
}
}
